captableinc/captable

- .env.example
- prisma/schema.prisma
> feat: add org and role table and setup associations between users, orgs and roles

- src/app/page.tsx
This pull request addresses and resolves issue #6 , which reports a horizontal scroll issue on the landing page, for windows browsers and some of the mobile browser.
> Fix horizontal scroll issue (#6)

- .env.example
- package-lock.json
- package.json
- src/emails/MagicLinkEmail.tsx
- src/emails/MemberInviteEmail.tsx
- src/env.js
- src/server/auth.ts
- src/server/mailer.ts
> feat: setup email templates

- package-lock.json
- package.json
- src/components/ui/uploader.tsx
- src/lib/utils.ts
- Built the UI for the Uploader with the `react-dropzone` library
> feat: Uploader UI Complete

- .env.example
- docker/docker-compose.yml
- package-lock.json
- package.json
- src/common/id.ts
- src/common/uploads.ts
- src/env.js
- src/server/file-uploads.ts
fixes #31. as tRPC doesn't support `multipart/form-data` this PR creates a utility to upload files from the client side using preSignedUrls and server actions
> feat: add file upload utility

- .env.example
- next.config.js
- src/app/(authenticated)/(onboarded)/dashboard/layout.tsx
- src/components/empty-state.tsx
- src/styles/globals.css
> feat: create an empty state component

- src/server/auth.ts
> feat: google OAuth fix

- package-lock.json
- package.json
- prisma/migrations/20240117213425_add_invited_email/migration.sql
- prisma/schema.prisma
- src/app/(authenticated)/(onboarded)/dashboard/stakeholders/page.tsx
- src/app/(authenticated)/verify-member/[token]/page.tsx
- src/components/shared/modal.tsx
- src/components/stakeholder/invite-member-modal/index.tsx
- src/components/stakeholder/member-card.tsx
- src/components/stakeholder/verify-member-form.tsx
- src/components/ui/avatar.tsx
- src/components/ui/dropdown-menu.tsx
- src/components/ui/separator.tsx
- src/components/ui/tabs.tsx
- src/emails/MemberInviteEmail.tsx
- src/env.js
- src/lib/crypto.ts
- src/server/auth.ts
- src/server/stakeholder.ts
- src/trpc/api/root.ts
- src/trpc/routers/stakeholder-router/router.ts
- src/trpc/routers/stakeholder-router/schema.ts
> feat: add invite member feature

- src/components/onboarding/login/index.tsx
- src/components/stakeholder/invite-member-modal/index.tsx
- src/components/stakeholder/verify-member-form.tsx
- src/components/ui/button.tsx
fixes: #57. this Pr adds loading state to the button
> feat: add loading state for button and use loading prop in form submission buttons

- prisma/schema.prisma
- src/app/(authenticated)/(onboarded)/[publicId]/captable/page.tsx
- src/app/(authenticated)/(onboarded)/[publicId]/equities/page.tsx
- src/app/(authenticated)/(onboarded)/[publicId]/layout.tsx
- src/app/(authenticated)/(onboarded)/[publicId]/page.tsx
- src/app/(authenticated)/(onboarded)/[publicId]/shares/page.tsx
- src/components/dashboard/navbar/command-menu.tsx
- src/components/dashboard/navbar/index.tsx
- src/components/dashboard/navbar/mobile-drawer.tsx
- src/components/dashboard/sidebar/index.tsx
- src/components/ui/select.tsx
> fix: broken links, navs and pages

- src/app/(authenticated)/(onboarded)/[publicId]/layout.tsx
- src/app/(authenticated)/(onboarded)/[publicId]/page.tsx
- src/app/(authenticated)/(onboarded)/[publicId]/stakeholders/page.tsx
- src/components/dashboard/sidebar/index.tsx
- src/components/shared/BorderWrapper.tsx
- src/components/shared/empty-state.tsx
- src/styles/globals.css
> feat: complete captable with CTA to get started

- src/components/stakeholder/member-modal.tsx
- src/components/stakeholder/member-table.tsx
- src/server/auth.ts
- src/server/stakeholder.ts
- src/trpc/api/trpc.ts
- src/trpc/routers/stakeholder-router/router.ts
- src/trpc/routers/stakeholder-router/schema.ts
fixes: #71
- only a admin can revoke invite or remove member
- only a admin can deactivate a user
- an admin can update stakeholders data
> feat: implement stakeholder update and access update features 

- src/components/onboarding/company.tsx
- src/components/stakeholder/member-modal.tsx
fixes #80
[Screencast 2024-01-29 13:55:17.webm](https://github.com/opencapco/opencap.co/assets/84864519/c347a24d-5a1c-4bb2-a1b8-0dc186bb2d46)
> fix: loading indicator not working for some forms

- src/app/(authenticated)/(dashboard)/company/new/page.tsx
- src/app/(authenticated)/(dashboard)/create-company/page.tsx
- src/components/dashboard/sidebar/company-switcher.tsx
- src/components/onboarding/company.tsx
- src/components/ui/select.tsx
> feat: add new company creation route

- src/app/(authenticated)/(dashboard)/[publicId]/stakeholders/page.tsx
- src/components/stakeholder/member-table.tsx
- src/server/stakeholder.ts
- src/trpc/routers/stakeholder-router/router.ts
- refactor the server queries to trpc
> refactor: use trpc for server calls

- package-lock.json
- package.json
- src/components/stakeholder/data.ts
- src/components/stakeholder/member-table-toolbar.tsx
- src/components/stakeholder/member-table.tsx
- src/components/ui/badge.tsx
- src/components/ui/data-table/data-table-faceted-filter.tsx
- src/components/ui/data-table/data-table-view-options.tsx
- src/components/ui/popover.tsx
fixes #98
[Screencast 2024-02-05 20:55:26.webm](https://github.com/opencapco/opencap.co/assets/84864519/a64e755c-af48-470d-8c24-a136d4118707)
> feat: add filters to stakeholder table

- .github/workflows/first-interaction.yml
this workflow greets the contributor while interacting with the repo for the first time
> feat: add first interaction workflow

- .github/workflows/semantic-pull-requests.yml
this pr validates PR title to follow conventional commit
credit - https://github.com/calcom/cal.com/blob/main/.github/workflows/semantic-pull-requests.yml
> feat: add semantic pull request workflow

- package.json
- src/app/(authenticated)/(dashboard)/[publicId]/audits/page.tsx
- src/app/(authenticated)/(dashboard)/[publicId]/page.tsx
- src/common/dayjs.ts
- src/components/audit/audit-table/audit-table-toolbar.tsx
- src/components/audit/audit-table/data.ts
- src/components/audit/audit-table/index.tsx
- src/components/dashboard/overview/activities-card.tsx
- src/components/stakeholder/member-table-toolbar.tsx
- src/components/stakeholder/member-table.tsx
- src/components/ui/alert.tsx
- src/components/ui/data-table/data-table-body.tsx
- src/components/ui/data-table/data-table-buttons.tsx
- src/components/ui/data-table/data-table-content.tsx
- src/components/ui/data-table/data-table-header.tsx
- src/components/ui/data-table/data-table-pagination.tsx
- src/components/ui/data-table/data-table-view-options.tsx
- src/components/ui/data-table/data-table.tsx
- src/trpc/api/root.ts
- src/trpc/routers/audit-router/router.ts
- src/trpc/routers/audit-router/schema.ts
[Screencast 2024-02-06 22:09:30.webm](https://github.com/opencapco/opencap.co/assets/84864519/a22425b9-5a71-4b69-8cc8-29c7d50145f0)
> feat: render audits on audits page

- README.md
- package.json
- prisma/migrations/20240206230113_update_share_class_migration/migration.sql
- prisma/migrations/20240207035312_optional_converts_to_share_class_id/migration.sql
- prisma/schema.prisma
- src/app/(authenticated)/(dashboard)/[publicId]/share-class/components/form.tsx
- src/app/(authenticated)/(dashboard)/[publicId]/share-class/new/page.tsx
- src/components/ui/use-toast.ts
- src/server/audit/actions.ts
- src/trpc/api/root.ts
- src/trpc/routers/onboarding-router/router.ts
- src/trpc/routers/share-class/router.ts
- src/trpc/routers/share-class/schema.ts
> feat: create share class

- prisma/migrations/20240208081440_add_work_email/migration.sql
- prisma/schema.prisma
- src/components/stakeholder/verify-member-form.tsx
- src/trpc/routers/stakeholder-router/procedures/accept-member.ts
- src/trpc/routers/stakeholder-router/schema.ts
- added workEmail field to the schema
- added work email field to the accept invitation form
> feat: require work email while accepting membership request

- prisma/seeds/index.ts
- src/app/(authenticated)/(dashboard)/[publicId]/equity-plans/form.tsx
- src/app/(authenticated)/(dashboard)/[publicId]/equity-plans/modal.tsx
- src/app/(authenticated)/(dashboard)/[publicId]/equity-plans/page.tsx
- src/app/(authenticated)/(dashboard)/[publicId]/equity-plans/table.tsx
- src/trpc/routers/equity-plan/router.ts
- src/trpc/routers/equity-plan/schema.ts
> feat: render and update equity plans

- src/app/(authenticated)/(dashboard)/[publicId]/documents/page.tsx
- src/app/(authenticated)/(dashboard)/[publicId]/documents/table.tsx
- src/components/shared/file-icon.tsx
- src/server/file-uploads.ts
> feat: cleanup document table and implement download feature

- src/app/(authenticated)/(dashboard)/[publicId]/templates/[templatePublicId]/page.tsx
- src/components/template/field-canvas/drawing-field.tsx
- src/components/template/field-canvas/index.tsx
- src/components/template/field-canvas/template-field.tsx
- src/trpc/routers/template-router/procedures/create-template.ts
[Screencast 2024-02-16 21:27:45.webm](https://github.com/opencapco/opencap.co/assets/84864519/5c3db6e7-c12d-4b33-86b9-e705306948e7)
> feat: add basic signing field canvas

- src/app/login/page.tsx
redirect user to dashboard if they are logged in, when they visit login page.
> fix: redirect user to dashboard

- src/app/(authenticated)/(dashboard)/[publicId]/(settings)/team/page.tsx
- src/components/member/member-table-toolbar.tsx
fixes #108 
@dahal there could be another better way to fix this bug. Let me know if you know a better fix than this one : )
> fix: stakeholder table ui fix

- src/components/dashboard/navbar/mobile-drawer.tsx
> fix: sidebar hamburger on medium screen

- src/server/audit/actions.ts
- src/server/audit/types.ts
- src/trpc/routers/document-router/procedures/create-document.ts
> fix: audit log document uploads

- src/app/providers/progress-bar.tsx
> fix: progess bar spinner removed

- src/components/template/canavs-toolbar/index.tsx
- src/components/template/field-canvas/template-field-container.tsx
- src/components/template/field-canvas/template-field.tsx
> feat: cleaning eSign flow a bit

- src/app/(authenticated)/(dashboard)/[publicId]/securities/safes/page.tsx
- src/components/safe/actions.tsx
- src/components/safe/existing/data.tsx
- src/components/safe/existing/modal.tsx
- src/components/safe/existing/safe-table-toolbar.tsx
- src/components/safe/existing/safe-table.tsx
- src/components/safe/existing/steps/documents.tsx
- src/components/safe/existing/steps/general-details.tsx
- src/components/safe/existing/steps/index.tsx
- src/components/safe/existing/steps/investor-details.tsx
- src/components/safe/existing/use-safe-steps.tsx
- src/trpc/routers/safe/procedures/add-existing-safe.ts
- src/trpc/routers/safe/router.ts
- src/trpc/routers/safe/schema.ts
> feat: Add existing SAFEs for stakeholders

- src/app/not-found.tsx
- build: 404 error page
fixes #210
> build: 404 error page

- prisma/migrations/20240501122457_esign_logs/migration.sql
- prisma/schema.prisma
- src/app/(authenticated)/(dashboard)/[publicId]/documents/esign/[templatePublicId]/page.tsx
- src/app/(authenticated)/(dashboard)/[publicId]/documents/esign/components/table.tsx
- src/app/(authenticated)/(dashboard)/[publicId]/documents/esign/v/[templatePublicId]/page.tsx
- src/server/audit/index.ts
- src/server/audit/schema.ts
- src/trpc/routers/audit-router/procedures/all-esign-audits.ts
- src/trpc/routers/audit-router/router.ts
- src/trpc/routers/audit-router/schema.ts
- src/trpc/routers/template-router/procedures/get-template.ts
- src/trpc/routers/template-router/procedures/sign-template.ts
- src/trpc/routers/template-router/schema.ts
> feat: add esign audit logs

- src/app/(authenticated)/(dashboard)/[publicId]/updates/page.tsx
- src/components/update/editor.tsx
- src/components/update/update-table-toolbar.tsx
- src/components/update/update-table.tsx
- src/trpc/routers/update/procedures/clone-update.ts
- src/trpc/routers/update/procedures/get-updates.ts
- src/trpc/routers/update/procedures/save-update.ts
- src/trpc/routers/update/procedures/save-updates.ts
- src/trpc/routers/update/router.ts
> feat: Render investor updates on a table and clone an update

- .lintstagedrc.cjs
- biome.json
current biome config is bloated and missing some of the rules from the eslint config. this PR add basic biome rules and some recommended rule.
> feat: add basic biome config

- src/components/onboarding/company-form.tsx
> fix: company form misalignment in xs-sm screen

- src/trpc/api/trpc.ts
> feat: Track Sentry metrics
